# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 10:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('author', models.CharField(max_length=30, null=True)),
                ('publication', models.CharField(max_length=30, null=True)),
                ('page', models.IntegerField(blank=True, null=True)),
                ('published', models.DateTimeField(null=True)),
                ('category', models.CharField(choices=[('eng', 'ENGINEERING'), ('doc', 'DOCTOR'), ('csit', 'CSIT'), ('arc', 'ARCHITECT'), ('ca', 'CHARTERED ACCOUNT')], default='eng', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(max_length=20)),
                ('batch', models.CharField(max_length=20)),
                ('contact_no', models.CharField(max_length=15, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
