# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elibrary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('returned', models.BooleanField(default=False)),
                ('return_date', models.DateTimeField(auto_now=True)),
                ('book', models.ManyToManyField(to='elibrary.Book')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elibrary.Student')),
            ],
        ),
    ]
