# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrary', '0002_bookrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrecord',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
